[package]
name = "velcro-derive"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
velcro-utils = {path = "../velcro-utils", version = "0.1.1"}
convert_case = "0.6.0"
proc-macro2 = "1.0.85"
quote = "1.0.10"
syn = "2.0.71"
darling = "0.20.9"